amcl:
  ros__parameters:
    alpha1: 0.2   # Expected process noise in odometry’s rotation estimate from rotation.
    alpha2: 0.05  # Expected process noise in odometry’s rotation estimate from translation.
    alpha3: 0.1   # Expected process noise in odometry’s translation estimate from translation.
    alpha4: 0.1   # Expected process noise in odometry’s translation estimate from rotation.
    alpha5: 0.05  # For Omni models only: translation noise.
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0  # Maximum distance to do obstacle inflation on map, for use in likelihood_field model.
    laser_max_range:  3.9
    laser_min_range: -1.0
    laser_model_type: "beam"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05               # Particle Filter population error.
    pf_z: 0.99                 # Particle filter population density.
    recovery_alpha_fast: 0.1   # Exponential decay rate for the fast average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.1.
    recovery_alpha_slow: 0.001 # Exponential decay rate for the slow average weight filter, used in deciding when to recover by adding random poses. A good value might be 0.001.
    resample_interval: 1       # Number of filter updates required before resampling.W
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /scan  # Filtered scan topic
    map_topic: map
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose: # Based on Gazebo turtlebot3_world.launch
      x: -2.0
      y: -0.5
      z: 0.0
      yaw: 0.0
