low_mid_level_planner:
  ros__parameters:
    expected_planner_frequency: 20.0
    distance_threshold: 5.0
    planner_plugin: 'GridBased'
    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner'

low_mid_level_planner_rclcpp_node:
  ros__parameters:
    use_sim_time: True
